[project]
name = "project-vault"
version = "1.0.0"
description = "The Unified Project Lifecycle Manager: Backup, Restore, and Teleport Projects Anywhere."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Dhruv", email = "your.email@example.com"}
]
dependencies = [
    "projectclone",
    "projectrestore",
    "boto3",
    "b2sdk",
    "rich",
    "tomli; python_version < '3.11'"
]

[project.scripts]
pv = "src.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src", "src.common"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
    "projectclone/tests",
    "projectrestore/tests",
]

addopts = [
    "--timeout=10",
    "--durations=10",
    "--log-cli-level=INFO",
    "-v",
    "-ra",
    "--tb=short",
    "--showlocals",
    "--strict-markers",
    "--cov=src",
    "--cov=projectclone",
    "--cov=projectrestore",
    "--cov-report=term-missing:skip-covered",
    "--cov-fail-under=97",
]

log_cli = true
log_cli_level = "INFO"

[tool.coverage.run]
branch = true
source = [
    "src",
    "projectclone",
    "projectrestore",
]

[tool.coverage.report]
show_missing = true